name: Deploy EKS Cluster

on:
  push:
    branches:
      - aws # Or your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest # Or specify a version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1 # Or your desired region

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/aws

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform/aws

      - name: Terraform Plan
        run: terraform plan -var-file=terraform.tfvars
        working-directory: terraform/aws
        continue-on-error: true #Allows plan to complete even if errors are found, so the output can be reviewed

      - name: Terraform Plan Output
        if: ${{ failure() && steps['Terraform Plan'].outcome == 'failure' }}
        run: exit 1 # Fail the workflow if terraform plan fails.

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=terraform.tfvars
        working-directory: terraform/aws
