apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jenkins.io
    chart: jenkins
    targetRevision: "4.1.3"  # Use a stable Jenkins chart version
    helm:
      values: |
        controller:
          serviceType: LoadBalancer  # Change to LoadBalancer
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: alb
              alb.ingress.kubernetes.io/group.name: argocd-jenkins
              alb.ingress.kubernetes.io/scheme: internet-facing
              alb.ingress.kubernetes.io/target-type: ip
              alb.ingress.kubernetes.io/backend-protocol: HTTP
            hostName: jenkins.k8s.it.com
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    syncOptions:
      - CreateNamespace=true    

