name: ArgoCD workflow

on:
  workflow_run:
    workflows: ["Terraform workflow"]
    types:
      - completed
  push:
    paths:
      - 'argocd/**'  

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TF_VAR_hosted_zone_id: ${{ secrets.AWS_HOSTED_ZONE_ID }}
      TF_VAR_certificate_arn: ${{ secrets.AWS_CERTIFICATE_ARN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Check if triggered by main branch
        id: check_branch
        run: |
          if [[ "${{ github.event.workflow_run.head_branch }}" != "main" ]]; then
            echo "This workflow was not triggered by the main branch. Exiting."
            exit 1
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name main-eks-cluster

      - name: Set up AWS CLI
        run: |
          sudo apt update
          sudo apt install -y aws-cli

      - name: Retrieve ALB Names from AWS SSM
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          echo "Fetching ALB Names from AWS SSM..."
          ARGOCD_ALB_NAME=$(aws ssm get-parameter --name "/terraform/argocd_alb_name" --query "Parameter.Value" --output text --region $AWS_REGION)
          JENKINS_ALB_NAME=$(aws ssm get-parameter --name "/terraform/jenkins_alb_name" --query "Parameter.Value" --output text --region $AWS_REGION)

          echo "ARGOCD_ALB_NAME=$ARGOCD_ALB_NAME" >> $GITHUB_ENV
          echo "JENKINS_ALB_NAME=$JENKINS_ALB_NAME" >> $GITHUB_ENV

      - name: Deploy ArgoCD
        run: |
          sed -i "s/PLACEHOLDER_ARGOCD_ALB_NAME/$ARGOCD_ALB_NAME/g" argocd/service.yaml
          kubectl apply -f argocd/namespace.yaml
          kubectl apply -f argocd/install.yaml
          kubectl apply -f argocd/service.yaml

      - name: Deploy Jenkins
        run: |
          sed -i "s/PLACEHOLDER_JENKINS_ALB_NAME/$JENKINS_ALB_NAME/g" jenkins/service.yaml
          kubectl apply -f jenkins/namespace.yaml
          kubectl apply -f jenkins/deployment.yaml
          kubectl apply -f jenkins/service.yaml
          
      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd-linux-amd64
          sudo mv argocd-linux-amd64 /usr/local/bin/argocd

      - name: Retrieve ArgoCD Admin Password
        run: |
          ARGOCD_PASSWORD=$(kubectl get secret -n argocd argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 --decode)
          echo "ARGOCD_PASSWORD=$ARGOCD_PASSWORD" >> $GITHUB_ENV

      - name: Login to ArgoCD
        run: |
          echo "Logging in to ArgoCD..."
          argocd login $ARGOCD_ALB_HOSTNAME --username admin --password $ARGOCD_PASSWORD --insecure

      - name: Add Private GitHub Repo to ArgoCD
        run: |
          argocd repo add https://github.com/MariusB-DevOps/k8s \
            --username "${{ secrets.GH_USERNAME }}" \
            --password "${{ secrets.GH_TOKEN }}" \
            --type git --insecure-skip-server-verification

      - name: Deploy application
        run: kubectl apply -f argocd/config/argocd-app.yaml
