name: ArgoCD workflow

on:
  workflow_run:
    workflows: ["Terraform workflow"]
    types:
      - completed
  push:
    paths:
      - 'argocd/**'  

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TF_VAR_hosted_zone_id: ${{ secrets.AWS_HOSTED_ZONE_ID }}
      TF_VAR_certificate_arn: ${{ secrets.AWS_CERTIFICATE_ARN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Check if triggered by main branch
        id: check_branch
        run: |
          if [[ "${{ github.event.workflow_run.head_branch }}" != "main" ]]; then
            echo "This workflow was not triggered by the main branch. Exiting."
            exit 1
          fi

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name main-eks-cluster

      - name: Ensure Jenkins Namespace Exists
        run: kubectl create namespace jenkins --dry-run=client -o yaml | kubectl apply -f -

          
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Initialize Terraform
        run: terraform init -reconfigure
        working-directory: terraform

      - name: Apply Terraform for ArgoCD and Jenkins
        run: terraform apply -auto-approve -target=helm_release.argocd -target=helm_release.jenkins
        working-directory: terraform/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Retrieve ArgoCD Server Address
        run: |
          ARGOCD_SERVER=$(kubectl get svc -n argocd argocd-server -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
          echo "ARGOCD_SERVER=$ARGOCD_SERVER" >> $GITHUB_ENV

      - name: Retrieve and Decode ArgoCD Admin Password from Cluster Secret
        run: |
          ARGOCD_PASSWORD=$(kubectl get secret argocd-initial-admin-secret -n argocd -o jsonpath="{.data.password}" | base64 --decode)
          echo "ARGOCD_PASSWORD=$ARGOCD_PASSWORD" >> $GITHUB_ENV

      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd-linux-amd64
          sudo mv argocd-linux-amd64 /usr/local/bin/argocd

      - name: Login to ArgoCD
        run: |
          argocd login $ARGOCD_SERVER --username admin --password $ARGOCD_PASSWORD --insecure --skip-test-tls --grpc-web

      - name: Add Private GitHub Repo to ArgoCD
        run: |
          argocd repo add https://github.com/MariusB-DevOps/k8s \
            --username "${{ secrets.GH_USERNAME }}" \
            --password "${{ secrets.GH_TOKEN }}" \
            --type git --insecure-skip-server-verification

      - name: Deploy application
        run: kubectl apply -f argocd/config/argocd-app.yaml
