name: Terraform Workflow
 
on:
 push:
   branches:
   - main
   paths:
   - terraform/**
  
jobs:
 terraform:
   name: "Terraform deploy"
   runs-on: ubuntu-latest
   env:
     TF_VAR_hosted_zone_id: ${{ secrets.AWS_HOSTED_ZONE_ID }}
     TF_VAR_certificate_arn: ${{ secrets.AWS_CERTIFICATE_ARN }}
   defaults:
     run:
       shell: bash
       # We keep Terraform files in the terraform directory.
       working-directory: ./terraform
 
   steps:
     - name: Checkout the repository to the runner
       uses: actions/checkout@v2
 
     - name: Setup Terraform with specified version on the runner
       uses: hashicorp/setup-terraform@v3
       with:
         terraform_version: 1.5.7
         terraform_wrapper: false
    
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v2
       with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

     - name: Terraform init
       id: init
       run: terraform init

     - name: Terraform format
       id: fmt
       run: terraform fmt -check
    
     - name: Terraform validate
       id: validate
       run: terraform validate

     - name: Terraform plan
       id: plan
       run: terraform plan -no-color -input=false
       continue-on-error: true
    
     - name: Terraform Apply
       run: terraform apply -auto-approve -input=false
     
     - name: Capture Terraform Output
       id: tf_output
       run: |
          terraform output -raw eks_connect > eks_connect.txt
          terraform output -raw argocd_alb_hostname > argocd_alb_hostname.txt
          terraform output -raw jenkins_alb_hostname > jenkins_alb_hostname.txt
          
     - name: Upload Terraform Output Artifact
       uses: actions/upload-artifact@v4
       with:
          name: terraform-output
          path: |
            ./terraform/eks_connect.txt
            ./terraform/argocd_alb_hostname.txt
            ./terraform/jenkins_alb_hostname.txt            
