name: Deploy EKS Cluster

on:
  push:
    branches:
      - aws # Or your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TF_VAR_iam_user_arn: ${{ secrets.IAM_USER_ARN }}
      TF_VAR_iam_role_arn: ${{ secrets.IAM_ROLE_ARN }}
      TF_VAR_assume_role_principal_arn: ${{ secrets.ASSUME_ROLE_PRINCIPAL_ARN }}
      TF_VAR_iam_username: ${{ secrets.IAM_USERNAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest # Or specify a version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1 # Or your desired region

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/aws

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform/aws

      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform/aws
        continue-on-error: true # Allows plan to complete even if errors are found, so the output can be reviewed

      - name: Terraform Plan Output
        if: ${{ failure() && steps['Terraform Plan'].outcome == 'failure' }}
        run: exit 1 # Fail the workflow if terraform plan fails.

      - name: Terraform Apply (Main)
        run: terraform apply -auto-approve -target=module.eks
        working-directory: terraform/aws

      - name: Extract Cluster Name
        id: extract-cluster-name
        run: |
          echo "::set-output name=cluster_name::$(terraform output -raw cluster_name)"
        working-directory: terraform/aws

      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ steps.extract-cluster-name.outputs.cluster_name }} --region eu-west-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Verify kubectl connection
        run: kubectl get nodes

      - name: Terraform Apply (aws-auth)
        run: terraform apply -target=module.eks_aws-auth -auto-approve
        working-directory: terraform/aws

