name: Deploy EKS Cluster

on:
  push:
    branches:
      - aws # Or your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest # Or specify a version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}          
          aws-region: eu-west-1

      - name: Terraform Init
        run: terraform init -reconfigure
        working-directory: terraform/eks

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform/eks

      - name: Terraform Plan
        run: terraform plan -out=terraform.tfplan
        working-directory: terraform/eks

      - name: Terraform Apply (Main)
        run: terraform apply -auto-approve
        working-directory: terraform/eks

      - name: Extract Cluster Name
        id: extract-cluster-name
        run: |
          echo "::set-output name=cluster_name::$(terraform output -raw cluster_name)"
        working-directory: terraform/eks

      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ steps.extract-cluster-name.outputs.cluster_name }} --region eu-west-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Verify kubectl connection
        run: kubectl get nodes
